# Generated by Django 5.2.8 on 2025-11-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='batch_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
    ]
